### ISSUE TITLE
Move CUDA installation to Relion playbook

### ISSUE THREAD

**Issue by darthweider** [KryoEM/AAProject#34]
move all plays/tasks for CUDA 8.0 installation inside of the Relion playbook.

edit the Relion playbook to check for CUDA 8.0 installation; and if not present, install it.

**Comment by kuybeda** [comment]
What is the status of this task?

**Comment by arestifo** [comment]
This task is finished, I just committed the playbook. It checks for the existence of `/usr/local/cuda` and skips the installation of the cuda toolkit if this directory is found.

**Comment by kuybeda** [comment]
Couldn't find CUDA installation when tried to reinstall Relion. What is the location of CUDA invocation in the ansible scripts?

**Comment by darthweider** [comment]
Will move CUDA installation to Relion playbook (from driver playbook).

Will also check for correct CUDA version with command "nvcc --version"

Should output something like:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Sun_Sep__4_22:14:01_CDT_2016
Cuda compilation tools, release 8.0, V8.0.44
```

Can then grep for version 8.0. 


I can try to get this done in the next couple of days, unless @a-re beats me to it.

**Comment by kuybeda** [comment]
Sounds good. It will save Alex some time. He then would use the updated
code fot testing the whole playbook on a fresh machine.

**Comment by darthweider** [comment]
Pushed the code for installing Cuda 8.0.

Fairly stringent parameters for checking for an existing version of 8.0 right now -- playbook will look only in the default non-interactive shell $PATH and the designated cuda install directory. Ensuring environment is correct is more tricky when the install location isn't initially known. Will work on a solution.

Also realized that we will need to install Cuda 7.5 as well to support MotionCor2, and will add that to the playbook soon.

In the meantime, as long as you comment out the tasks for installing MotionCor2, the playbook should be operational.

**Comment by kuybeda** [comment]
MotionCor2 is not as critical as the full pass through, which needs only
unblur_tbz. If it takes longer than couple hours, let's postpone this task
to a later time.

**Comment by kuybeda** [comment]
Also, I would do cuda 7.5 in a separate book/file, like together with the
install of MotionCor2, in order to make the Nvidia drivers script a clean
install point for basic system wide Nvidia environment, which can be used
separately from Relion install.

On Feb 1, 2017 1:39 AM, "darthweider" <notifications@github.com> wrote:

Pushed the code for installing Cuda 8.0.

Fairly stringent parameters for checking for an existing version of 8.0
right now -- playbook will look only in the default non-interactive shell
$PATH and the designated cuda install directory. Ensuring environment is
correct is more tricky when the install location isn't initially known.
Will work on a solution.

Also realized that we will need to install Cuda 7.5 as well to support
MotionCor2, and will add that to the playbook soon.

In the meantime, as long as you comment out the tasks for installing
MotionCor2, the playbook should be operational.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/KryoEM/AAProject/issues/34#issuecomment-276529366>, or mute
the thread

**Comment by darthweider** [comment]
To clarify: should the CUDA8.0 installation be in the drivers playbook or the Relion install playbook?

**Comment by darthweider** [comment]
Cuda8.0 installation now in the drivers playbook again.

Variables that require user input are in the inventory file, along with the host names. (Therefore, if the user changes the host names to match their machine configuration, they will also see the 2 path variables they need to check.)

Drivers playbook will check for existing Cuda 8.0 installation. If installation is not found, it will prompt user to confirm that they want to continue with the installation.


Relion playbook will also check for existing Cuda 8.0. if installation not found, will pause and wait for user to confirm that they want to proceed with a non-GPU installation.
