### ISSUE TITLE
Create template Relion submission script

### ISSUE THREAD

**Issue by darthweider** [KryoEM/AAProject#35]
Template submission script should be OpenMPI compatible and export a CUDA-8.0 environment.

See: https://www2.mrc-lmb.cam.ac.uk/relion/index.php/Download_%26_install#Set-up_queue_job_submission
especially this example script: https://www2.mrc-lmb.cam.ac.uk/relion/index.php/Manual_machinefile_script_example

The Biowulf submission script to sbatch:
/usr/local/apps/RELION2.0/2.0.1/relion_sbatch.sh

**Comment by kuybeda** [comment]
As discussed, this script will set the environment first, then call the actual program. 

Maybe, it would be a good idea first to source /etc/profile.d from this script as well. This will avoid the need to change global /etc/bashrc  for setting environment for non-interactive shells. 

If sourcing /etc/profile.d doesn't work, because there are unrelated scripts that interfere with our project, all our script might be moved to a separate location in /etc/aaproject.d and sourced from there

**Comment by darthweider** [comment]
See #41 and #45

**Comment by kuybeda** [comment]
Is resolved by adding "bash -l " to each relion command.
